dist: trusty
sudo: false

language: node_js
node_js:
  - "13.6.0"

addons:
    chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run test:cover -- --watch=false --progress=false --browsers=ChromeHeadlessCI
  - npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js

after_success:
   - npm run coveralls
   - npm run build:gh-pages:test1


deploy:
  provider: pages:git
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: gh-pages
  on:
    branch: feat/gh-pages-with-travis  

